config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'

  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!

    def index
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_user!

    def index
        @projects = Project.all
    end

    def show
        @project = Project.find(params['id'])
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.new(permitted_params)
        if @project.save
            redirect_to project_path(@project)
        else
            render :new
        end
    end

    def edit
    end

    def update 
    end

    protected 

    def permitted_params
        params.require(:project).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title MyBascamp1
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload"
    = javascript_include_tag "rails-ujs"
  %body
    - if user_signed_in?
      = link_to "Log out", destroy_user_session_path, method: :delete
    = yield

app/views/projects/index.html.haml
Projects #Index

= link_to "New Project", new_project_path
%br

- @projects.each do |project|
    = link_to project.name, project_path(project)
    %br

app/views/projects/new.html.haml
Project #New

= simple_form_for @project do |f|
    = f.input :name
    = f.submit

app/views/projects/show.html.haml
Project #Show

= link_to "Project index", projects_path

%br

= @project.name